---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  annotations:
    defaultVolumeType: local
  name: aditya-storageclass
provisioner: rancher.io/local-path 
reclaimPolicy: Delete 
volumeBindingMode: WaitForFirstConsumer

  

