
apiVersion: v1 
kind: LimitRange
metadata: 
    name: test-lr-01
spec:
    limits:
        - type: Pod
          min:
              cpu: 100m
              memory: 100Mi
          max:
              cpu: 200m
              memory: 200Mi



--- 
apiVersion: v1 
kind: LimitRange
metadata: 
    name: test 
spec: 
    limits:
        - type: PersistentVolumeClaim
          min:
              storage: 100Mi
          max:
              storage: 200Mi
          default:
              storage: 200Mi
