apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deploy
  name: test-deploy
  namespace: testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-deploy
#----------------------------
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
#------------------------------
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      
      - image: nginx:1.18
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
#-----------------------------
        livenessProbe:
          exec: 
            command:
            - /bin/sh
            - -c
            - curl http://127.0.0.1
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
#---------------------------------
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
#--------------------------------------
        env:
          - name: SECRET 
            valueFrom:
              secretKeyRef:
                name:  sec1
                key: s1 
#-------------------------------------
        envFrom:
          - configMapRef:
              name: cm1
          - secretRef: 
              name: sec1 
#--------------------------------------
        volumeMounts:
            - name: sec-vol
              mountPath: /etc/secret
       
            - name: cm-volume
              mountPath: /etc/cm
#------------------------------------            
#        volumeMounts:
#          - name: cm-volume
#            mountPath: /etc/config
#      volumes:
#        - name: cm-volume
#          configMap:
#            name: cm1 
#----------------------------------
      volumes:
          - name: sec-vol
            secret:
              secretName: sec1
          - name: cm-volume
            configMap:
              name: cm1
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30

