apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/ece-test-images/agnhost:2.40
    args:
    - liveness
    livenessProbe:
      httpGet:
        path: /Healthz # the probe sends http get request to this endpoint
        port: 8080 # on this port 
      initialDelaySeconds: 60 # initial start after 60 seconds 
      periodSeconds: 10 # will be executed every 10 seconds
      timeoutSeconds: 5 # will be executed after 5 seconds
      failureThreshold: 3 # container is restarted if it fails 3 consecutive times
